name: Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          [
            identity-service,
            catalog-service,
            cart-service,
            order-service,
            billing-service,
            notification-service,
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.service }}

      - name: Run tests
        run: npm test || true
        working-directory: ${{ matrix.service }}
